/**
 * @author Adrian Yao <adrianYao@augmentum.com.cn>
 * @version 1.6
 * @since 2014 Mar 27, 2014
 */
package com.augmentum.ec.core.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CartProductId generated by hbm2java.
 */
@Embeddable
public final class CartProductId implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 3754694839559650177L;

    /** The cart id. */
    private Long cartId;

    /** The product id. */
    private Integer productId;

    /**
     * Instantiates a new cart product id.
     */
    public CartProductId() {
    }

    /**
     * Gets the cart id.
     *
     * @return the cart id
     */
    @Column(name = "cart_id", nullable = false)
    public Long getCartId() {
        return this.cartId;
    }

    /**
     * Sets the cart id.
     *
     * @param cartId the new cart id
     */
    public void setCartId(final Long cartId) {
        this.cartId = cartId;
    }

    /**
     * Gets the product id.
     *
     * @return the product id
     */
    @Column(name = "product_id", nullable = false)
    public Integer getProductId() {
        return this.productId;
    }

    /**
     * Sets the product id.
     *
     * @param productId the new product id
     */
    public void setProductId(final Integer productId) {
        this.productId = productId;
    }

    /*
     * (non-Javadoc)
     *
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(final Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof CartProductId)) {
            return false;
        }
        CartProductId castOther = (CartProductId) other;

        return (this.getCartId() == castOther.getCartId()) && (this.getProductId() == castOther.getProductId());
    }

    /*
     * (non-Javadoc)
     *
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (cartId != null ? cartId.intValue() : 0);
        result = 37 * result + this.getProductId();
        return result;
    }

}
